### ISSUE TITLE
Missing files for the wiki

### ISSUE THREAD

**Issue by lunadragnstar** [ldtteam/MinecoloniesWiki#250]
missing files

postbox icon is missing from MinecoloniesWiki/assets/images/icons/minecolonies/
blockhutarchery is missing from MinecoloniesWiki/assets/images/icons/minecolonies/
blockhutcrusher block is missing from MinecoloniesWiki/assets/images/icons/minecolonies/
blockhutsifter block is missing from MinecoloniesWiki/assets/images/icons/minecolonies/
blockhutstonesmeltery block is missing from MinecoloniesWiki/assets/images/icons/minecolonies/
blockmultiblock block is missing from MinecoloniesWiki/assets/images/icons/minecolonies/

stone missing from MinecoloniesWiki/assets/images/icons/minecraft/
redstone_block missing from MinecoloniesWiki/assets/images/icons/minecraft/
piston missing from MinecoloniesWiki/assets/images/icons/minecraft/

**Comment by Wissi** [comment]
The images that are missing are all the new blocks. 
They need to be rendered from the newest JAR and screenshot then uploaded.

**Comment by KryssLB** [comment]
Hi guys, love the mod!!

The Sawmill recipe is missing from the Sawmill page, and under misc/Recipes it gives the one for the Lumberjack instead (7 wood/building tool/wooden axe). Noticed that the graphic for the Lumberjack recipe there also is giving the Mining one instead of the Lumberjack one, as is the one for the Town Hall.

Thanks for the great work!!
