### ISSUE TITLE
more of a request

### ISSUE THREAD

**Issue by ShdwDvl** [ldtteam/MinecoloniesWiki#260]
is there anywhere that have the dimensions of what the buildings are or can it get put in the wiki

**Comment by Wissi** [comment]
There was in the original Wiki a sort of description of what materials were needed for every building, but that has not been ported over due to the extreme amount of schematics and styles.
That being explained, I'll respond: No. 
We will NOT add the dimensions or blocks contained in every single building and level. it is not going to be possible. They are player made and player submitted and is growing and changing and expandind as new workers come out as well. So it is not even feasable to waste our time there, as changes are and will be made to them always.
Use the building tool and view the level 5 of each building and each style you want to see the dimensions.
