### ISSUE TITLE
New Update

### ISSUE THREAD

**Issue by cynaverda** [ldtteam/MinecoloniesWiki#261]
The most recent update to Minecolonies made all of my worlds disappear. I have spent 4 weeks on a build in one of those worlds. Is there any way to get them back or is it gone forever?

**Comment by someaddons** [comment]
no mod update can ever make your world disappear, you must've lost them some other way, like deleting the saves/world folder or sth like this.

**Comment by cynaverda** [comment]
I played on the same profile on twitch before I went to work. When I came home and updated, the worlds were gone. Nothing else was touched or changed.

**Comment by Wissi** [comment]
It is a known issue that Twitch will not update correctly and sometimes erase all folders and do a clean install instead of an update.
We always recommend making a new separate install so hat you could just copy over your folders:
saves, journeymap, structurize and any personal config file in the config folder.

I'm sorry you are another person that has had lost saves due to Twitch issues.
Closing this as it is NOT a WIKI issue. Please reopen in the minecolonies Github if you feel you still need more help.
