### ISSUE TITLE
Update research system page

### ISSUE THREAD

**Issue by anonymous563** [ldtteam/MinecoloniesWiki#747]
## Page(s)

https://wiki.minecolonies.ldtteam.com/source/systems/research

## Information Missing

At least the nether miner unlock and druid-based research are missing]

Tasks:
List out the things that are missing
Update the images with current research trees
Update the text to include current research
-- what the research is called, what it does, what it requires

**Comment by Nikademus** [comment]
I was looking over the research page to see if I can update it.  There are times when it looks like things are cumulative, and times when it looks like they aren't.
For example: Band Aid gives +10% Regen, Healing says +15%, the wiki says it's 25% (cumulative).
Resistance says saturation -0.5, Resilience says saturation -0.5, the wiki says -1.0 (cumulative).
However, Outpost says +25 citizens, Hamlet says +50 citizens, the wiki says +75 instead of +100 (not cumulative).

How do we know when it's cumulative or not?

**Comment by MotionlessTrain** [comment]
I think the numbers *with* percentages replace each other (e.g. regen) and the number *without* percentages add up (e.g. the saturation values and number of citizens)
